### ISSUE TITLE
[Question] Is there a way to customize property threshold for new lines?

### ISSUE THREAD

**Issue by whaaaley** [kutsan/stylelint-config-clean-order#13]
I saw in another issue that it was maybe possible to adjust the property threshold before lines get added. Just curious if there's a way to adjust that threshold.
Thanks!

**Comment by kutsan** [comment]
Hi, currently there isn't a way to optionally set the threshold without forking the whole project. I'd like to keep the options at their reasonable defaults. Besides, as far as I know there isn't a clean way to make this since it's a JSON config and you can't really accept user input. It needs to be like below and I don't like the look of it.

```
{
  "extends": ["stylelint-config-clean-order", "stylelint-config-clean-order/minimal-threshold"]
}

**Comment by wimhendrikx** [comment]
There is a way using a JS stylelint config: `stylelint.config.js`. Also not ideal but it works.

```
const cleanOrderConfig = require('stylelint-config-clean-order');

// Overwrite threshold
cleanOrderConfig.rules['order/properties-order'][1]["emptyLineMinimumPropertyThreshold"] = 5;

module.exports = cleanOrderConfig;
```

**Comment by kutsan** [comment]
I'm closing this issue as there are no current plans to implement the requested feature. Thanks!
